/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : bigint,
  'title' : string,
  'date' : Time,
  'description' : string,
  'location' : string,
}
export interface Article {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : Time,
  'imageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export interface TeamMember {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'role' : string,
  'imageUrl' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'createArticle' : ActorMethod<
    [string, string, string, string, string],
    Article
  >,
  'deleteArticle' : ActorMethod<[bigint], undefined>,
  'getActivities' : ActorMethod<[], Array<Activity>>,
  'getActivity' : ActorMethod<[bigint], Activity>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getArticle' : ActorMethod<[bigint], Article>,
  'getTeamMember' : ActorMethod<[bigint], TeamMember>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'updateArticle' : ActorMethod<
    [bigint, string, string, string, string, string],
    Article
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];