/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'imageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const GaleriItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'tanggal' : Time,
  'description' : IDL.Text,
  'mediaUrl' : IDL.Text,
  'mediaType' : IDL.Text,
});
export const PendaftaranAnggota = IDL.Record({
  'id' : IDL.Nat,
  'nik' : IDL.Text,
  'status' : IDL.Text,
  'alamat' : IDL.Text,
  'alasan' : IDL.Text,
  'nama' : IDL.Text,
  'email' : IDL.Text,
  'pekerjaan' : IDL.Text,
  'tanggalDaftar' : Time,
  'phone' : IDL.Text,
});
export const SatuanSSK = IDL.Record({
  'id' : IDL.Nat,
  'alamat' : IDL.Text,
  'nama' : IDL.Text,
  'deskripsi' : IDL.Text,
  'email' : IDL.Text,
  'logoUrl' : IDL.Text,
  'phone' : IDL.Text,
  'ketua' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const VideoYoutube = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'youtubeId' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'operationalHours' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Profile = IDL.Record({
  'tagline' : IDL.Text,
  'misi' : IDL.Text,
  'visi' : IDL.Text,
  'deskripsi' : IDL.Text,
  'namaOrganisasi' : IDL.Text,
});
export const ProgramUnggulan = IDL.Record({
  'kecamatanTerlayani' : IDL.Text,
  'judul' : IDL.Text,
  'deskripsi' : IDL.Text,
  'penghargaan' : IDL.Text,
  'programKegiatan' : IDL.Text,
  'pesertaTerlatih' : IDL.Text,
});
export const SiteSettings = IDL.Record({ 'logoUrl' : IDL.Text });
export const SliderBanner = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'linkUrl' : IDL.Text,
  'urutan' : IDL.Nat,
});


export const idlService = IDL.Service({
  'createActivity' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Text],
      [Activity],
      [],
    ),
  'createArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Article],
      [],
    ),
  'createGaleriItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [GaleriItem],
      [],
    ),
  'createPendaftaran' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [PendaftaranAnggota],
      [],
    ),
  'createSatuanSSK' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SatuanSSK],
      [],
    ),
  'createSliderBanner' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [SliderBanner],
      [],
    ),
  'createTeamMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [TeamMember],
      [],
    ),
  'createVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [VideoYoutube], []),
  'deleteActivity' : IDL.Func([IDL.Nat], [], []),
  'deleteSliderBanner' : IDL.Func([IDL.Nat], [], []),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'deleteGaleriItem' : IDL.Func([IDL.Nat], [], []),
  'deletePendaftaran' : IDL.Func([IDL.Nat], [], []),
  'deleteSatuanSSK' : IDL.Func([IDL.Nat], [], []),
  'deleteTeamMember' : IDL.Func([IDL.Nat], [], []),
  'deleteVideo' : IDL.Func([IDL.Nat], [], []),
  'getActivity' : IDL.Func([IDL.Nat], [Activity], ['query']),
  'getAllActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getAllSliderBanners' : IDL.Func([], [IDL.Vec(SliderBanner)], ['query']),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAllGaleriItems' : IDL.Func([], [IDL.Vec(GaleriItem)], ['query']),
  'getAllPendaftaran' : IDL.Func([], [IDL.Vec(PendaftaranAnggota)], ['query']),
  'getAllSatuanSSK' : IDL.Func([], [IDL.Vec(SatuanSSK)], ['query']),
  'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(VideoYoutube)], ['query']),
  'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getProfile' : IDL.Func([], [Profile], ['query']),
  'getProgramUnggulan' : IDL.Func([], [ProgramUnggulan], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getTeamMember' : IDL.Func([IDL.Nat], [TeamMember], ['query']),
  'updateActivity' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, Time, IDL.Text],
      [Activity],
      [],
    ),
  'updateArticle' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Article],
      [],
    ),
  'updateContactInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ContactInfo],
      [],
    ),
  'updateGaleriItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [GaleriItem],
      [],
    ),
  'updatePendaftaranStatus' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [PendaftaranAnggota],
      [],
    ),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Profile],
      [],
    ),
  'updateProgramUnggulan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ProgramUnggulan],
      [],
    ),
  'updateSatuanSSK' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [SatuanSSK],
      [],
    ),
  'updateSliderBanner' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [SliderBanner],
      [],
    ),
  'registerAdmin' : IDL.Func([], [IDL.Bool], []),
  'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetAdmin' : IDL.Func([], [IDL.Bool], []),
  'forceResetAdmin' : IDL.Func([], [IDL.Bool], []),
    'updateSiteSettings' : IDL.Func([IDL.Text], [SiteSettings], []),
  'updateTeamMember' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [TeamMember],
      [],
    ),
  'updateVideo' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [VideoYoutube],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'imageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const GaleriItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'tanggal' : Time,
    'description' : IDL.Text,
    'mediaUrl' : IDL.Text,
    'mediaType' : IDL.Text,
  });
  const PendaftaranAnggota = IDL.Record({
    'id' : IDL.Nat,
    'nik' : IDL.Text,
    'status' : IDL.Text,
    'alamat' : IDL.Text,
    'alasan' : IDL.Text,
    'nama' : IDL.Text,
    'email' : IDL.Text,
    'pekerjaan' : IDL.Text,
    'tanggalDaftar' : Time,
    'phone' : IDL.Text,
  });
  const SatuanSSK = IDL.Record({
    'id' : IDL.Nat,
    'alamat' : IDL.Text,
    'nama' : IDL.Text,
    'deskripsi' : IDL.Text,
    'email' : IDL.Text,
    'logoUrl' : IDL.Text,
    'phone' : IDL.Text,
    'ketua' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const VideoYoutube = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'youtubeId' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'operationalHours' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Profile = IDL.Record({
    'tagline' : IDL.Text,
    'misi' : IDL.Text,
    'visi' : IDL.Text,
    'deskripsi' : IDL.Text,
    'namaOrganisasi' : IDL.Text,
  });
  const ProgramUnggulan = IDL.Record({
    'kecamatanTerlayani' : IDL.Text,
    'judul' : IDL.Text,
    'deskripsi' : IDL.Text,
    'penghargaan' : IDL.Text,
    'programKegiatan' : IDL.Text,
    'pesertaTerlatih' : IDL.Text,
  });
  const SiteSettings = IDL.Record({ 'logoUrl' : IDL.Text });
  const SliderBanner = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'linkUrl' : IDL.Text,
    'urutan' : IDL.Nat,
  });
  
  return IDL.Service({
    'createActivity' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Text],
        [Activity],
        [],
      ),
    'createArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Article],
        [],
      ),
    'createGaleriItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [GaleriItem],
        [],
      ),
    'createPendaftaran' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [PendaftaranAnggota],
        [],
      ),
    'createSatuanSSK' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [SatuanSSK],
        [],
      ),
    'createSliderBanner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [SliderBanner],
        [],
      ),
    'createTeamMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [TeamMember],
        [],
      ),
    'createVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [VideoYoutube],
        [],
      ),
    'deleteActivity' : IDL.Func([IDL.Nat], [], []),
  'deleteSliderBanner' : IDL.Func([IDL.Nat], [], []),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'deleteGaleriItem' : IDL.Func([IDL.Nat], [], []),
    'deletePendaftaran' : IDL.Func([IDL.Nat], [], []),
    'deleteSatuanSSK' : IDL.Func([IDL.Nat], [], []),
    'deleteTeamMember' : IDL.Func([IDL.Nat], [], []),
    'deleteVideo' : IDL.Func([IDL.Nat], [], []),
    'getActivity' : IDL.Func([IDL.Nat], [Activity], ['query']),
    'getAllActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getAllSliderBanners' : IDL.Func([], [IDL.Vec(SliderBanner)], ['query']),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAllGaleriItems' : IDL.Func([], [IDL.Vec(GaleriItem)], ['query']),
    'getAllPendaftaran' : IDL.Func(
        [],
        [IDL.Vec(PendaftaranAnggota)],
        ['query'],
      ),
    'getAllSatuanSSK' : IDL.Func([], [IDL.Vec(SatuanSSK)], ['query']),
    'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(VideoYoutube)], ['query']),
    'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getProfile' : IDL.Func([], [Profile], ['query']),
    'getProgramUnggulan' : IDL.Func([], [ProgramUnggulan], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getTeamMember' : IDL.Func([IDL.Nat], [TeamMember], ['query']),
    'updateActivity' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, Time, IDL.Text],
        [Activity],
        [],
      ),
    'updateArticle' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Article],
        [],
      ),
    'updateContactInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ContactInfo],
        [],
      ),
    'updateGaleriItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [GaleriItem],
        [],
      ),
    'updatePendaftaranStatus' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [PendaftaranAnggota],
        [],
      ),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Profile],
        [],
      ),
    'updateProgramUnggulan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ProgramUnggulan],
        [],
      ),
    'updateSatuanSSK' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [SatuanSSK],
        [],
      ),
    'updateSliderBanner' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [SliderBanner],
      [],
    ),
  'updateSiteSettings' : IDL.Func([IDL.Text], [SiteSettings], []),
    'updateTeamMember' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [TeamMember],
        [],
      ),
    'updateVideo' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [VideoYoutube],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };