/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'imageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'imageUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'createArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Article],
      [],
    ),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'getActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getActivity' : IDL.Func([IDL.Nat], [Activity], ['query']),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
  'getTeamMember' : IDL.Func([IDL.Nat], [TeamMember], ['query']),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'updateArticle' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Article],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'imageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'createArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Article],
        [],
      ),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'getActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getActivity' : IDL.Func([IDL.Nat], [Activity], ['query']),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
    'getTeamMember' : IDL.Func([IDL.Nat], [TeamMember], ['query']),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'updateArticle' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Article],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };