/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SliderBanner {
    id: bigint;
    title: string;
    linkUrl: string;
    description: string;
    imageUrl: string;
    urutan: bigint;
}
export type Time = bigint;
export interface SiteSettings {
    logoUrl: string;
}
export interface GaleriItem {
    id: bigint;
    title: string;
    tanggal: Time;
    description: string;
    mediaUrl: string;
    mediaType: string;
}
export interface VideoYoutube {
    id: bigint;
    title: string;
    description: string;
    youtubeId: string;
}
export interface ProgramUnggulan {
    kecamatanTerlayani: string;
    judul: string;
    deskripsi: string;
    penghargaan: string;
    programKegiatan: string;
    pesertaTerlatih: string;
}
export interface Activity {
    id: bigint;
    title: string;
    date: Time;
    description: string;
    location: string;
}
export interface TeamMember {
    id: bigint;
    bio: string;
    name: string;
    role: string;
    imageUrl: string;
}
export interface SatuanSSK {
    id: bigint;
    alamat: string;
    nama: string;
    deskripsi: string;
    email: string;
    logoUrl: string;
    phone: string;
    ketua: string;
}
export interface Profile {
    tagline: string;
    misi: string;
    visi: string;
    deskripsi: string;
    namaOrganisasi: string;
}
export interface PendaftaranAnggota {
    id: bigint;
    nik: string;
    status: string;
    alamat: string;
    alasan: string;
    nama: string;
    email: string;
    pekerjaan: string;
    tanggalDaftar: Time;
    phone: string;
}
export interface ContactInfo {
    operationalHours: string;
    email: string;
    address: string;
    phone: string;
}
export interface Article {
    id: bigint;
    title: string;
    content: string;
    date: Time;
    imageUrl: string;
    excerpt: string;
    category: string;
}
export interface backendInterface {
    createActivity(title: string, description: string, date: Time, location: string): Promise<Activity>;
    createArticle(title: string, excerpt: string, content: string, category: string, imageUrl: string): Promise<Article>;
    createGaleriItem(title: string, description: string, mediaUrl: string, mediaType: string): Promise<GaleriItem>;
    createPendaftaran(nama: string, nik: string, alamat: string, phone: string, email: string, pekerjaan: string, alasan: string): Promise<PendaftaranAnggota>;
    createSatuanSSK(nama: string, alamat: string, phone: string, email: string, deskripsi: string, logoUrl: string, ketua: string): Promise<SatuanSSK>;
    createSliderBanner(title: string, description: string, imageUrl: string, linkUrl: string, urutan: bigint): Promise<SliderBanner>;
    createTeamMember(name: string, role: string, bio: string, imageUrl: string): Promise<TeamMember>;
    createVideo(title: string, youtubeId: string, description: string): Promise<VideoYoutube>;
    deleteActivity(id: bigint): Promise<void>;
    deleteArticle(id: bigint): Promise<void>;
    deleteGaleriItem(id: bigint): Promise<void>;
    deletePendaftaran(id: bigint): Promise<void>;
    deleteSatuanSSK(id: bigint): Promise<void>;
    deleteSliderBanner(id: bigint): Promise<void>;
    deleteTeamMember(id: bigint): Promise<void>;
    deleteVideo(id: bigint): Promise<void>;
    forceResetAdmin(): Promise<boolean>;
    getActivity(id: bigint): Promise<Activity>;
    getAdminPrincipal(): Promise<Principal | null>;
    getAllActivities(): Promise<Array<Activity>>;
    getAllArticles(): Promise<Array<Article>>;
    getAllGaleriItems(): Promise<Array<GaleriItem>>;
    getAllPendaftaran(): Promise<Array<PendaftaranAnggota>>;
    getAllSatuanSSK(): Promise<Array<SatuanSSK>>;
    getAllSliderBanners(): Promise<Array<SliderBanner>>;
    getAllTeamMembers(): Promise<Array<TeamMember>>;
    getAllVideos(): Promise<Array<VideoYoutube>>;
    getArticle(id: bigint): Promise<Article>;
    getContactInfo(): Promise<ContactInfo>;
    getProfile(): Promise<Profile>;
    getProgramUnggulan(): Promise<ProgramUnggulan>;
    getSiteSettings(): Promise<SiteSettings>;
    getTeamMember(id: bigint): Promise<TeamMember>;
    isCallerAdmin(): Promise<boolean>;
    registerAdmin(): Promise<boolean>;
    resetAdmin(): Promise<boolean>;
    updateActivity(id: bigint, title: string, description: string, date: Time, location: string): Promise<Activity>;
    updateArticle(id: bigint, title: string, excerpt: string, content: string, category: string, imageUrl: string): Promise<Article>;
    updateContactInfo(address: string, phone: string, email: string, operationalHours: string): Promise<ContactInfo>;
    updateGaleriItem(id: bigint, title: string, description: string, mediaUrl: string, mediaType: string): Promise<GaleriItem>;
    updatePendaftaranStatus(id: bigint, status: string): Promise<PendaftaranAnggota>;
    updateProfile(namaOrganisasi: string, tagline: string, deskripsi: string, visi: string, misi: string): Promise<Profile>;
    updateProgramUnggulan(judul: string, deskripsi: string, pesertaTerlatih: string, programKegiatan: string, penghargaan: string, kecamatanTerlayani: string): Promise<ProgramUnggulan>;
    updateSatuanSSK(id: bigint, nama: string, alamat: string, phone: string, email: string, deskripsi: string, logoUrl: string, ketua: string): Promise<SatuanSSK>;
    updateSiteSettings(logoUrl: string): Promise<SiteSettings>;
    updateSliderBanner(id: bigint, title: string, description: string, imageUrl: string, linkUrl: string, urutan: bigint): Promise<SliderBanner>;
    updateTeamMember(id: bigint, name: string, role: string, bio: string, imageUrl: string): Promise<TeamMember>;
    updateVideo(id: bigint, title: string, youtubeId: string, description: string): Promise<VideoYoutube>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createActivity(arg0: string, arg1: string, arg2: Time, arg3: string): Promise<Activity> {
        if (this.processError) {
            try {
                const result = await this.actor.createActivity(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createActivity(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createArticle(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Article> {
        if (this.processError) {
            try {
                const result = await this.actor.createArticle(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArticle(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createGaleriItem(arg0: string, arg1: string, arg2: string, arg3: string): Promise<GaleriItem> {
        if (this.processError) {
            try {
                const result = await this.actor.createGaleriItem(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGaleriItem(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createPendaftaran(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<PendaftaranAnggota> {
        if (this.processError) {
            try {
                const result = await this.actor.createPendaftaran(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPendaftaran(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createSatuanSSK(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<SatuanSSK> {
        if (this.processError) {
            try {
                const result = await this.actor.createSatuanSSK(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSatuanSSK(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createSliderBanner(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<SliderBanner> {
        if (this.processError) {
            try {
                const result = await this.actor.createSliderBanner(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSliderBanner(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createTeamMember(arg0: string, arg1: string, arg2: string, arg3: string): Promise<TeamMember> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeamMember(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeamMember(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createVideo(arg0: string, arg1: string, arg2: string): Promise<VideoYoutube> {
        if (this.processError) {
            try {
                const result = await this.actor.createVideo(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVideo(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteActivity(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteActivity(arg0);
            return result;
        }
    }
    async deleteArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArticle(arg0);
            return result;
        }
    }
    async deleteGaleriItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGaleriItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGaleriItem(arg0);
            return result;
        }
    }
    async deletePendaftaran(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePendaftaran(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePendaftaran(arg0);
            return result;
        }
    }
    async deleteSatuanSSK(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSatuanSSK(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSatuanSSK(arg0);
            return result;
        }
    }
    async deleteSliderBanner(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSliderBanner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSliderBanner(arg0);
            return result;
        }
    }
    async deleteTeamMember(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeamMember(arg0);
            return result;
        }
    }
    async deleteVideo(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async forceResetAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.forceResetAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.forceResetAdmin();
            return result;
        }
    }
    async getActivity(arg0: bigint): Promise<Activity> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivity(arg0);
            return result;
        }
    }
    async getAdminPrincipal(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPrincipal();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPrincipal();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActivities(): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActivities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActivities();
            return result;
        }
    }
    async getAllArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArticles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArticles();
            return result;
        }
    }
    async getAllGaleriItems(): Promise<Array<GaleriItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGaleriItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGaleriItems();
            return result;
        }
    }
    async getAllPendaftaran(): Promise<Array<PendaftaranAnggota>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPendaftaran();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPendaftaran();
            return result;
        }
    }
    async getAllSatuanSSK(): Promise<Array<SatuanSSK>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSatuanSSK();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSatuanSSK();
            return result;
        }
    }
    async getAllSliderBanners(): Promise<Array<SliderBanner>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSliderBanners();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSliderBanners();
            return result;
        }
    }
    async getAllTeamMembers(): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeamMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeamMembers();
            return result;
        }
    }
    async getAllVideos(): Promise<Array<VideoYoutube>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideos();
            return result;
        }
    }
    async getArticle(arg0: bigint): Promise<Article> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticle(arg0);
            return result;
        }
    }
    async getContactInfo(): Promise<ContactInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactInfo();
            return result;
        }
    }
    async getProfile(): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return result;
        }
    }
    async getProgramUnggulan(): Promise<ProgramUnggulan> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgramUnggulan();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgramUnggulan();
            return result;
        }
    }
    async getSiteSettings(): Promise<SiteSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteSettings();
            return result;
        }
    }
    async getTeamMember(arg0: bigint): Promise<TeamMember> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamMember(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAdmin();
            return result;
        }
    }
    async resetAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAdmin();
            return result;
        }
    }
    async updateActivity(arg0: bigint, arg1: string, arg2: string, arg3: Time, arg4: string): Promise<Activity> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActivity(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActivity(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateArticle(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<Article> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArticle(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArticle(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateContactInfo(arg0: string, arg1: string, arg2: string, arg3: string): Promise<ContactInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContactInfo(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContactInfo(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateGaleriItem(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<GaleriItem> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGaleriItem(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGaleriItem(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updatePendaftaranStatus(arg0: bigint, arg1: string): Promise<PendaftaranAnggota> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePendaftaranStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePendaftaranStatus(arg0, arg1);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateProgramUnggulan(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<ProgramUnggulan> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProgramUnggulan(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProgramUnggulan(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateSatuanSSK(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<SatuanSSK> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSatuanSSK(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSatuanSSK(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateSiteSettings(arg0: string): Promise<SiteSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteSettings(arg0);
            return result;
        }
    }
    async updateSliderBanner(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint): Promise<SliderBanner> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSliderBanner(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSliderBanner(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateTeamMember(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<TeamMember> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamMember(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamMember(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateVideo(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<VideoYoutube> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideo(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideo(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
